# Import Library & Read dataset

In [53]:
import pandas as pd
import numpy as np
import seaborn as sns

In [54]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Dataset/emails.csv')
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [55]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [58]:
df.drop_duplicates(inplace=True)

In [59]:
df['spam'].value_counts()

0    4327
1    1368
Name: spam, dtype: int64

In [60]:
df.isnull().sum()

text    0
spam    0
dtype: int64

# Separate X & Y for dependent & Independent value

In [61]:
x = df.text.values

In [64]:
y = df.spam.values #Dependent

# split dataset

In [65]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y, test_size=0.2)

# Data preprocessing

In [66]:
from sklearn.feature_extraction.text import CountVectorizer

In [67]:
cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# Naive Bayes Algorithm

In [68]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train,ytrain)

x_test = cv.transform(xtest)

In [69]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0]])

In [70]:
model.score(x_test,ytest)

0.9920983318700615

In [77]:
emails = ['hey i am looking for a car driver','I will pay him after work as free giveaway as servey']

In [78]:
cv_emails = cv.transform(emails)

In [79]:
model.predict(cv_emails)

array([0, 0])

In [80]:
pred = model.predict(x_test)

pred

array([0, 0, 0, ..., 0, 0, 0])

In [82]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,pred)

0.9920983318700615

# Random Forest Algorithm

In [83]:
from sklearn.ensemble import RandomForestClassifier

In [84]:
classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, max_depth=5, n_estimators=100, oob_score=True)

In [85]:
classifier_rf.fit(x_train,ytrain)

RandomForestClassifier(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)

In [86]:
classifier_rf.oob_score_

0.7914837576821774

In [87]:
rf = RandomForestClassifier(random_state=42, n_jobs=-1)

In [88]:
jalal = {
    'max_depth': [2,3,5,10,20],
    'min_samples_leaf': [5,10,20,50,100,200],
    'n_estimators': [10,25,30,50,100,200]
}

In [89]:
from sklearn.model_selection import GridSearchCV

In [90]:
grid_search = GridSearchCV(estimator=rf,
                           param_grid=jalal,
                           cv = 4,
                           n_jobs=-1, verbose=1, scoring="accuracy")

In [91]:
grid_search.fit(x_train, ytrain)

Fitting 4 folds for each of 180 candidates, totalling 720 fits


GridSearchCV(cv=4, estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [2, 3, 5, 10, 20],
                         'min_samples_leaf': [5, 10, 20, 50, 100, 200],
                         'n_estimators': [10, 25, 30, 50, 100, 200]},
             scoring='accuracy', verbose=1)

In [92]:
grid_search.best_score_

0.8887181738366988